insert into application(id,name,url,sid) values (1,'日记','/home/application/diary/','diary')
,(2,'专栏','/home/application/diary/','column')
,(3,'职业生涯','/home/application/diary/','column1')
,(4,'文本库','/home/application/diary/','column1')
,(5,'案例库','/home/application/diary/','column1')
,(6,'我的客户','/home/application/diary/','column1')
,(7,'成本控制','/home/application/diary/','column1')
,(8,'订阅','/home/application/diary/','column1')
,(9,'律师招聘','/home/application/diary/','column1')
,(10,'律师猎头','/home/application/diary/','column1')
,(11,'报告','/home/application/diary/','column1')
,(12,'调研','/home/application/diary/','column1')
,(13,'个人年度报告','/home/application/diary/','column1')
,(14,'提醒','/home/application/diary/','column1')
,(15,'手机计划','/home/application/diary/','column1')
,(16,'在线资讯','/home/application/diary/','column1')
,(17,'专家库','/home/application/diary/','column1')
,(18,'专栏','/home/application/diary/','column1')
,(19,'高端访谈','/home/application/diary/','column1')
,(20,'个人名片','/home/application/diary/','column1')
,(21,'个人动态消息','/home/application/diary/','column1')
,(22,'我的课程','/home/application/diary/','column1')
,(23,'培训计划','/home/application/diary/','column1')
,(24,'个人客户关系管理','/home/application/diary/','column1')
,(25,'个人品牌建设','/home/application/diary/','column1')
,(26,'个人市场推广','/home/application/diary/','column1')
,(27,'IT Suport','/home/application/diary/','column1');

insert into application_role (application_id,role,is_default,is_free) values
(1,0,1,1)
,(2,0,1,1)
