CREATE TABLE `lawsive`.`images` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255)  DEFAULT NULL COMMENT '标题',
  `description` TEXT  COMMENT '简介',
  `url` VARCHAR(255)  DEFAULT NULL COMMENT '地址',
  `category_id` INT(10) UNSIGNED DEFAULT NULL COMMENT '类别ID',
  `keywords` VARCHAR(255)  DEFAULT NULL COMMENT '关键词',
  `tags` VARCHAR(255)  DEFAULT NULL COMMENT '标签',
  `publisher` VARCHAR(45)  DEFAULT NULL COMMENT '发布者',
  `created_at` DATETIME  DEFAULT NULL COMMENT '创建时间',
  `click_count` INT(10) UNSIGNED DEFAULT 0 COMMENT '点击量',
  `is_adopt` TINYINT(1) UNSIGNED DEFAULT 0 COMMENT '是否发布',
  `priority` INT(10) UNSIGNED DEFAULT 100 COMMENT '优先级',
  `src` VARCHAR(255)  DEFAULT NULL COMMENT '图片地址',
  `thumb_name` VARCHAR(255)  DEFAULT NULL COMMENT '缩略图',
  `src2` VARCHAR(255)  DEFAULT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = MyISAM;

