ALTER TABLE `lawsive`.`lawyer_project` MODIFY COLUMN `name` VARCHAR(500)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '项目名称',
 MODIFY COLUMN `project_type` VARCHAR(256)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '项目性质',
 MODIFY COLUMN `value` VARCHAR(30)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '项目金额',
 MODIFY COLUMN `client` VARCHAR(500)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '客户',
 MODIFY COLUMN `result` VARCHAR(1000)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '项目结果',
 MODIFY COLUMN `income` VARCHAR(20)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '客户收益',
 MODIFY COLUMN `project_period` VARCHAR(20)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '项目周期',
 MODIFY COLUMN `comment` TEXT  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户评价',
 MODIFY COLUMN `law_in` VARCHAR(256)  CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '使用哪国法律，中间使用/分割'
, CHARACTER SET utf8 COLLATE utf8_general_ci;
