ALTER TABLE `lawsive`.`member` MODIFY COLUMN `login_name` VARCHAR(128)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '登录名',
 MODIFY COLUMN `email` VARCHAR(128)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '邮箱地址';
