ALTER TABLE `lawsive`.`member_education_history` MODIFY COLUMN `college` VARCHAR(128)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '学校',
 MODIFY COLUMN `start_date` VARCHAR(50)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '开始时间',
 MODIFY COLUMN `end_date` VARCHAR(50)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '结束时间',
 MODIFY COLUMN `description` VARCHAR(512)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '描述';
