ALTER TABLE `lawsive`.`member_job_history` MODIFY COLUMN `company` VARCHAR(128)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '公司',
 MODIFY COLUMN `title` VARCHAR(255)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '职务',
 MODIFY COLUMN `start_date` VARCHAR(50)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '开始时间',
 MODIFY COLUMN `end_date` VARCHAR(50)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '结束时间',
 MODIFY COLUMN `description` VARCHAR(512)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '描述';

