ALTER TABLE `lawsive`.`member` MODIFY COLUMN `login_name` VARCHAR(48)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '登录名',
 MODIFY COLUMN `password` VARCHAR(50)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '密码',
 MODIFY COLUMN `name` VARCHAR(50)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '昵称',
 MODIFY COLUMN `email` VARCHAR(256)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '邮箱地址',
 MODIFY COLUMN `avatar` VARCHAR(256)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '头像',
 MODIFY COLUMN `cache_name` CHAR(20)  CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '登录后的标示',CHARACTER SET utf8 COLLATE utf8_general_ci;

